openapi: 3.0.0
info:
  title: Stock Price Viewer API
  description: Used to get Stock information for a Quote
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/JayanthKumar/StockPriceViewer/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /stock:
    get:
      tags:
      - stock
      summary: Get stock price for all the quote
      operationId: getStocks
      responses:
        "405":
          description: Invalid input
      x-swagger-router-controller: Stock
    post:
      tags:
      - stock
      summary: Update stock price for a quote
      operationId: postStock
      responses:
        "405":
          description: Invalid input
        "201":
          description: created successfully
      x-swagger-router-controller: Stock
  /stock/{quoteId}:
    get:
      tags:
      - stock
      summary: Get stock price for a specific quote
      operationId: getStock
      parameters:
      - name: quoteId
        in: path
        description: ID of quote to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Successfully returned
        "401":
          description: Quote doesn't exist
      x-swagger-router-controller: Stock
components: {}
